=== abhisekp/conf42-golang-2023-building-cli-app/internal/cmd/output.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Persona">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="Name" type="xs:string"/>
                <xs:element minOccurs="0" name="DateCreated" type="xs:string"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="Person">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" name="FirstName" type="xs:string"/>
                            <xs:element minOccurs="0" name="LastName" type="xs:string"/>
                            <xs:element minOccurs="0" name="Street" type="xs:string"/>
                            <xs:element minOccurs="0" name="City" type="xs:string"/>
                            <xs:element minOccurs="0" name="Pincode" type="xs:string"/>
                            <xs:element minOccurs="0" name="State" type="xs:string"/>
                            <xs:element minOccurs="0" name="Country" type="xs:string"/>
                            <xs:element minOccurs="0" name="Age" type="xs:string"/>
                            <xs:element minOccurs="0" name="Dob" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== abhisekp/conf42-golang-2023-building-cli-app/output.example.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persona xsi:noNamespaceSchemaLocation="./output.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Example</Name>
  <DateCreated>2023-04-09T16:46:35+05:30</DateCreated>
  <Person>
    <FirstName>Ollie</FirstName>
    <LastName>Kihn</LastName>
    <Street>63527 Circles view</Street>
    <City>Hialeah</City>
    <Pincode>18866</Pincode>
    <State>Delaware</State>
    <Country>American Samoa</Country>
    <Age>5</Age>
  </Person>
  <Person>
    <FirstName>Davonte</FirstName>
    <LastName>Goyette</LastName>
    <Street>2754 Lake Island furt</Street>
    <City>Philadelphia</City>
    <Pincode>99645</Pincode>
    <State>Oklahoma</State>
    <Country>United States of America</Country>
    <Age>11</Age>
  </Person>
</Persona>
